### ISSUE TITLE
multiple builder callbacks that match the same k8s object will only cause the first one to be called.

### ISSUE THREAD

**Issue by bdw617** [defenseunicorns/pepr#311] opened 2023-10-11 20:20 UTC
### Is your feature request related to a problem? Please describe.

at `npx pepr dev/build` identify if multiple builder callbacks could match the same object. 

```
When(a.ConfigMap)
  .IsCreated()
  .Mutate(request => {
      // will only be called for Created() requests
  });

When(a.ConfigMap)
  .IsCreatedOrUpdated()
  .Mutate(request => {
  // will only be called for Updated() requests but not Created() requests
  });
```

example 2:
```
// this will always be called, regardless of the data.
When(a.ConfigMap)
  .IsCreatedOrUpdated()
  .Mutate(request => {
      if (request.Raw.data?.["hello"]) {
        // DO SOMETHING
      }
  });

// this will NEVER be called, regardless of the data.
When(a.ConfigMap)
  .IsCreatedOrUpdated()
  .Mutate(request => {
      if (!request.Raw.data?.["hello"]) {
        // DO SOMETHING ELSE
      }
  });

// THIS IS THE CORRECT WAY:
When(a.ConfigMap)
  .IsCreatedOrUpdated()
  .Mutate(request => {
      if (request.Raw.data?.["hello"]) {
        // DO SOMETHING
      } else {
         // DO SOMETHING ELSE
      }
  });
```

if multiple builders match the same object, only the first one will be called. We don't chain them (and we do it silently, which is confusing)

**Comment by cmwylie19** [comment] 2023-10-17 13:52
_Revised to confirm to Feature Request Template:_


### Describe the solution you'd like

- **Given** a user has multiple actions operating on the same resource
- **When** `npx pepr dev/build` is issued
- **Then** the problem is identified by Pepr Core and the dev run/build fails describing the problem to the user

### Describe alternatives you've considered
(optional) A clear and concise description of any alternative solutions or features you've considered.

### Additional context
Add any other context or screenshots about the feature request here.

**Comment by jeff-mccoy** [comment] 2023-10-23 06:33
This should be chained right now--are we sure they are not? If you're running in a debugger, you very well could run into issues if you're not careful with multiple at once, but we don't do anything to reduce the action callbacks that I'm aware of currently.

**Comment by cmwylie19** [comment] 2023-11-15 12:56
Assigning this for a spike, going to investigate this statement by @jeff-mccoy. There is an remedy for this through identification of the bindings

**Comment by bdw617** [comment] 2023-11-20 15:31
I woke up and it occurred to me how to fix this, so I've created a PR that demonstrates the behavior change. Since depending on the application, the problem may never happen, warn might be the right approach.

**Comment by cmwylie19** [comment] 2023-11-29 23:11
![image](https://github.com/defenseunicorns/pepr/assets/1096507/e26ba2ac-d39c-49bd-b462-0217a6bbcdfc)


![image](https://github.com/defenseunicorns/pepr/assets/1096507/bf5f5d81-7122-413d-a445-ed441e2146ed)


We are not able to reproduce any issue here, it seems like they are both being called in the even the case of overlap. We recently submitted a PR for chaining Validates that simplify the process of multiple validates operating on the same resource. We are closing this for now but feel free to open back up should there be a need. 

https://github.com/defenseunicorns/pepr/pull/405

**Closed as completed by cmwylie19** 2023-11-29 23:11 UTC
Labels: enhancement
